### ISSUE TITLE
Add timestamp for DID chain widget

### ISSUE THREAD

**Issue by sgreenbury** [alan-turing-institute/trustchain-mobile#14]
Add the display of the date and time for the timestamp associated with the root DID of a DID chain to the DID chain widget. See equivalent issue for [GUI](https://github.com/alan-turing-institute/trustchain-gui/issues/2)

**Comment by thobson88** [comment]
[PR open](https://github.com/alan-turing-institute/trustchain-mobile/pull/53)

**Comment by sgreenbury** [comment]
Closed with #53
