### ISSUE TITLE
Display resolved user DID on tap

### ISSUE THREAD

**Issue by lukehare** [alan-turing-institute/trustchain-mobile#22]
Add a widget (gesture detector?) to make the user's DID, shown at the bottom of the profile page, into a button that then displays the resolved DID including pub keys (this is already implemented for the credential detail page when you tap on the issuer).

**Comment by sgreenbury** [comment]
Next steps:
- [ ] Refine the button to resolver user did
- [ ] Consider whether display should be:
    - Entire expanded DID doc with JSON
    - Subset of DID doc (did, key) with JSON
    - A new widget with DID, key, etc
