### ISSUE TITLE
Root event time as date

### ISSUE THREAD

**Issue by pwochner** [alan-turing-institute/trustchain-mobile#26]
Allow root event time to be input as date (with new FFI call or endpoint to query)

**Comment by thobson88** [comment]
I've started this (assuming the FFI route) in the trustchain-ion crate on branch [`root-event-date`](https://github.com/alan-turing-institute/trustchain/tree/root-event-date).

**Comment by thobson88** [comment]
Server-side finished & [PR open](https://github.com/alan-turing-institute/trustchain/pull/125).

I've started the `trustchain-mobile` implementing on branch `feat/26-root-event-date` (branched off of `dev`).

**Comment by thobson88** [comment]
[PR also open](https://github.com/alan-turing-institute/trustchain-mobile/pull/49) on `trustchain-mobile`.
